### ISSUE TITLE
Meeting Minutes

### ISSUE THREAD

**Issue by niiita** [Lercerss/SOEN341W18#10]
##SPRINT 1
1. Login --> sign-up / registration
     *1. Login with facebook / google? (API)
     *1. Form
2. Welcome page
      (Front end)
      *2. Set up local host
      *2. Set up server
      *2. HTML CSS JavaScript.
3. Ask a question
4. Answer
5. Voting
6. Choosing right answer
7. Commenting
8. Validation (user/post)

**Comment by niiita** [comment]
WRAP UP
-can propose special features
-make sure process is standard and everything is standard

WORKING ENVIRONMENT:
-issue already done by ALVYN
	-everyone test it works
-can set up environment

have all issues layed out
descriptive
complex issues can be broken down
comment directly on commit

LUCAS: create Issue template
HANNA: create SCRUM template
EVERYONE else create issue from list
slack choice.

**Comment by riyaGit** [comment]
Google Docs: https://docs.google.com/document/d/1RQyCAg2bhxS5wOMH1PN4FRaHnilsFwiMNOSIdGGrwMM/edit

Slack: https://soen341-sa3.slack.com/messages/C8RFUBAJD/ 

Grading Scheme: 

# Date: 2 Feb 2018

**location:** LB 209

**time:** 11am

**attendees:** ALL present
  1. Due 14th FEB for all
        - Do the issue
       - Meeting next wednesday --room TBD

  
  **issue proposed**
  1. diff. b/w commenting and answering questions: comments are not answers-- not in the main thread -> answers are top level replies and comments are sub-level replies
  1. Will should "rebase" to be able to merge his branch --in the end will is going to end up deleting the whole login folder
  1. **BOOTSTRAP for front-end**
  
  **issue discussed**
  1. Always have 2 people review code before merging [REVIEWING IS IMPORTANT!!!] -leave a comment while reviewing
  1. "Accepting and rejecting answers" -part of "choosing best answer"
  1. put the bootstrap files in the Repo (eg: CSS files)
  1. CDN (Content delivery network) : it 
  1. Everytime you make a commit REFERENCE the issue number!
  
  **Tasks assigned to specific people**
  1. Brinda: welcome page
  1. Hanna: answering questions
  1. Alvyn: Commenting
  1. Will: Login registration (authentication) - back-end (Alvyn wants to help)
  1. Peter: choosing best answer
  1. Patrick: voting 
  1. Riya: Posting questions
  1. Lucas: validation

**Comment by Lercerss** [comment]
This has been moved to the wiki.
