### ISSUE TITLE
Fix tabs in question index

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#100]
## Description
The tabs at the top of the questions index (Latest, Hottest, Most Votes) are not functional right now. 
  - Story points: 1
  - Priority: High
  - Risk: Medium

## Tasks
  1. Implement sorting of questions.
  1. Tie tab selection to ordering of questions displayed by the paginator.

**Comment by Lercerss** [comment]
As we are running low on time and the deadline for Sprint 4 is closing in, we could also consider simply removing it entirely.

**Comment by alvyn279** [comment]
All the necessary conversation is found in PR #107.
