### ISSUE TITLE
Set up Django working environment

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/SOEN341W18#11]
## Description
Working Django environment for every team member's computer.

  - Story Points: 3 
  - Priority: High
  - Risk: Low

## Acceptance Test
  1. Display running website page
 
## Tasks
  1. Create one copy of requirements file (Lucas)
  1. **pip install -r requirements.txt**
  1. Create Django project locally and push to remote (one person)
  1. Fetch and checkout the new branch from repo to obtain Django project (all assignees)
  1. **python manage.py runserver** OR **python3 manage.py runserver**
  1. Set up the database with at least one table and Admin Interface (**one person**)

**Comment by alvyn279** [comment]
## Preview of successfully installed local running server
![image](https://user-images.githubusercontent.com/29107916/35468043-417c30fe-02e5-11e8-9bf5-ce9a4c807513.png)

**Comment by niiita** [comment]
Preview of successfully installed local running server on any browser at http://localhost:8000
![image](https://user-images.githubusercontent.com/35353909/35468570-bfeeee0a-02ee-11e8-9f24-b45e39a496aa.png)

**Comment by pvacca97** [comment]
Preview of running Django environment at [http://localhost:8000](url)

![screenshot from 2018-01-27 12-46-00](https://user-images.githubusercontent.com/35609091/35474750-8891532c-0360-11e8-9cae-f9a21f4903a7.png)

**Comment by Belize22** [comment]
Preview of Django environment running at http://localhost:8000
![it worked](https://user-images.githubusercontent.com/14872794/35478106-c81fedea-03a2-11e8-964d-9fd8f6d63f45.png)

**Comment by Lercerss** [comment]
Preview of Django environment running locally.
![django_startup](https://user-images.githubusercontent.com/34099471/35478874-efba5ef8-03b6-11e8-8826-d3df6bdc3cab.png)

**Comment by riyaGit** [comment]
Preview of Django environment running locally.

![image](https://user-images.githubusercontent.com/26652806/35490090-0ff99594-046b-11e8-8904-7eead4079260.png)

**Comment by jetcanfly** [comment]
![image](https://user-images.githubusercontent.com/18118928/35595116-8dadd792-05e3-11e8-8412-c6f572b7157f.png)
Preview of Django environment running locally.

**Comment by 13rinda** [comment]
<img width="836" alt="screen shot 2018-01-30 at 7 00 16 pm" src="https://user-images.githubusercontent.com/31190776/35598244-3d2f917c-05f0-11e8-8294-ef0c9f4258b5.png">

**Comment by Lercerss** [comment]
![image](https://user-images.githubusercontent.com/34099471/37225052-61731e8e-23a3-11e8-9174-ac8843c2e0ce.png)
