### ISSUE TITLE
Enhance user experience in User Profile

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/SOEN341W18#110]
## Description
The user profile is not completely satisfying in terms of user experience at the moment. When editing a profile, we cannot access our initial information in every single field; one would be required to fill everything back up. In the recent answers and comments, we do not see the question/answer pertaining to it.

  - Story points: 2
  - Priority: Medium
  - Risk: Medium

## Tasks
  1. Make the edit profile form pre-filled with existing values.
  1. Implement a small link back to the parent of the answer/comments.

**Comment by Lercerss** [comment]
Implemented as part of #111.
