### ISSUE TITLE
add quick_search window to navbar

### ISSUE THREAD

**Issue by jetcanfly** [Lercerss/SOEN341W18#113]
## Description
[This is an enhancement of #71. Instead of using a independent page, we add a quick_search window on nav bar for quick access to search. Input keywords in that window and click enter. ] 
  - Story points: [1]
  - Priority: [Low]
  - Risk: [Low]

## Tasks
  1. add a window to navbar.
  2. adjust searching page and only show results.

## Acceptance Test
  1. Input keywords in quick_search windows and click enter to jump to searching result page .
  2. Go through Acceptance Test in #71 using quick_search window and check the result in result page. The results should be the same as #71 .

**Comment by Lercerss** [comment]
Implemented as part of #114.
