### ISSUE TITLE
Remove duplicate meeting notes

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#12]
## Description
Settle on a single meeting notes file as well as a single template for these notes. 
  - Story points: 0
  - Priority: Medium
  - Risk: Low

## Tasks 
  1. Consolidate notes into single file
  1. Confirm meeting template 
  1. Remove unnecessary duplicate meeting notes 

Make sure to refer to this issue when committing.

**Comment by Lercerss** [comment]
We might want to use this opportunity to clean up the Test.txt file as well

**Comment by riyaGit** [comment]
I removed my meeting minutes so there is only one now. And i updated the MEETING_TEMPLATE so we can review that now. Plus not sure what you mean by cleaning up the test file? Do we just delete it?

**Comment by Lercerss** [comment]
Yes, since it was simply for the initial pull requests we can delete it now. Thank you!

**Comment by riyaGit** [comment]
Great! So I guess we are done for this part.
