### ISSUE TITLE
"Post questions" feature

### ISSUE THREAD

**Issue by riyaGit** [Lercerss/SOEN341W18#15]
## Description
Allow users to ask questions 
  - Story points: 3
  - Priority: High
  - Risk: Low

## Tasks
  1. Dialog box for user to post question.
  1. Submit button to post question.
  1. Edit button to edit the question.
  1. Voting button for questions #14 
  1. Label showing the username of the user who posted the question.

## Acceptance Test
  1. Write question in dialog box and submit to post question.
  1. Notice that the a question is posted showing the username of the user that posted the question.
  1. Edit the question and submit again.
  1. Notice that the change is made to the question.

**Comment by Lercerss** [comment]
#37 solved this issue.

**Comment by Belize22** [comment]
![issue 15](https://user-images.githubusercontent.com/14872794/37225054-619a7d8a-23a3-11e8-98d4-a24fe4f35e73.png)
