### ISSUE TITLE
Add commenting feature

### ISSUE THREAD

**Issue by jetcanfly** [Lercerss/SOEN341W18#19]
## Description
[Allow users to comment to questions and answers. Each comment consists of content, author, timestamp.] 
  - Story points: [3]
  - Priority: [Medium]
  - Risk: [Medium]

## Tasks
  1. Add 'Add a comment' button below both question section and answer section. Only for users.
  2. A message box will show up after a user clicking adding button, below which is a 'save' button.
  3. After clicking 'Save', user's input will be shown as a comment.
  4. Add 'delete' button only visible to comment author. 
  5. After adding or deleting comments the layout of the page will adjust automatically. 

## Acceptance Test
  1. For non-users, they can't see 'add a comment'
  2. Log in as a user and add comment to a question. Check the format.
  3. Delete the comment in step 2.
  4. Log in as a user and add comment to a answer. Check the format.
  5. Delete the comment in step 4.
  6. Add several comments and delete one randomly. Check the format.

**Comment by Belize22** [comment]
You may wanna add this to Sprint 2 instead. Adding comments is considered a core feature and core features are part of Sprint 2.

**Comment by jetcanfly** [comment]
@Belize22 I think this may not be the core feature. And this feature has some dependencies on 'posting question' and 'posting answer'. Unless those two features are completed early in sprint 2, we may not have enough time for this feature in sprint 2.

**Comment by 13rinda** [comment]
Yes, I agree, that it is not necessarily a core feature and so we should leave it out for Sprint 2.

**Comment by Lercerss** [comment]
Is this issue fully implemented @Belize22? If so please close it with a reference to the pull request, thanks!

**Comment by niiita** [comment]
https://github.com/StackExchange/pagedown

**Comment by Belize22** [comment]
![issue 19](https://user-images.githubusercontent.com/14872794/37572413-03c255ee-2ae1-11e8-8b11-f3d29ebf672f.png)
