### ISSUE TITLE
Choosing Best Answer

### ISSUE THREAD

**Issue by Belize22** [Lercerss/SOEN341W18#20]
## Description
Allow a user who posted a question to choose the best answer that helped them and to deselect this best answer if the user changes their mind.
  - Story points: 3
  - Priority: Low
  - Risk: Low

## Tasks
  1. For all comments in a question, implement a "Select as Best Answer" Button. These buttons should only appear if no best answer is selected yet.
  2. If a best answer exists within a question page, put this answer above all other comments.
  3. Implement a "Deselect as Best Answer" Button. It should only appear when a best answer exists and only on the comment chosen as the best answer.
  4. Make sure "Select as Best Answer" does not appear if a best answer is already selected and "Deselect as Best Answer" does not appear if a best answer doesn't exist.
  5. Ensure Tasks 1, 3 and 4 are only visible to the user that asked the question.

## Acceptance Test
  1. Open a question page that has no best answer without being logged in. Ensure that "Select as Best Answer" does not appear. Repeat this step logged in as a user who didn't ask the question.
  3. Login as the user who asked the question and verify that "Select as Best Answer" exists for every comment in the question.
  4. Choose "Select as Best Answer" for any comment. Verify that all instances of "Select as Best Answer" are gone and that the best answer now has a "Deselect as Best Answer" button.
  5. Log out then check the question page to verify that "Deselect as Best Answer" is not displayed. Repeat this step logged in as a user who didn't ask the question.
  6. Login as the user who asked the question and click "Deselect as Best Answer". Make sure what used to be best answer is now part of the other comments. Verify that all instances of "Select as Best Answer" exist.

**Comment by 13rinda** [comment]
On the same not, if the answer did not help, can we add the opposite feature? For example, thumbs up if it helped and "THUMBS DOWN" if it did not help?

**Comment by Belize22** [comment]
What you suggested is dedicated to the voting feature. The idea of best answer is to allow the user to select what helped them best, regardless of the amount of votes a particular answer has.

**Comment by alvyn279** [comment]
This was completed through PR #45 . This issue is now closed.

**Comment by alvyn279** [comment]
![image](https://user-images.githubusercontent.com/29107916/37226891-6395d304-23a9-11e8-8862-618af3c426c6.png)
