### ISSUE TITLE
Validation 

### ISSUE THREAD

**Issue by 13rinda** [Lercerss/SOEN341W18#25]
Description

Validate the features are well functioning and deliver what was intended for it to do. 
Story points: 2
Priority: High
Risk: Low

Tasks

Check each feature individually upon its implementation. 
Ensure that the initial requirement was met by this feature.
For each feature, read upon its issue and ensure that the tasks were completed and that it passes its specific feature testing.
If the feature does not meet the requirement or fails one of the componential tests, return to the requirement stage and implement precisely what is required. 
In order to move on successfully with each test, all the tasks for the feature's issue must be completed in its entirety. 
 

Acceptance Test

If the feature is stable and functioning upon testing different cases if needed, move on to testing the next feature or next stage. 
The tested cases must test for exceptional cases, or cases which may throw any errors. If this is done correctly the feature is stable and most importantly fulfils its requirements. 

Test Cases : Provide some cases tested

**Comment by 13rinda** [comment]
[Sign up _ TestCases.pdf](https://github.com/Lercerss/SOEN341W18/files/1711768/Sign.up._.TestCases.pdf)

**Comment by Lercerss** [comment]
Not relevant to the project anymore.
