### ISSUE TITLE
Answering Questions

### ISSUE THREAD

**Issue by niiita** [Lercerss/SOEN341W18#26]
# **Description**
Allow users to answer questions.
Answer must include author and time-stamp.
Must somewhat verify validity.

- Story points:  3
- Priority: High
- Risk: Medium

# **Tasks**

1. "Login" button to post answer.
2. Dialog box for user to post answer.
3. "Post answer" button to post answer to the question.
4. "Edit" button for poster to edit the answer.
5. "Vote" button for validity of answer.
6. Label showing the username of the poster who answered. (Maybe a user icon?)
7. Counter for number of answers posted for given question.

# **Acceptance Test**

1. Ensure "Active" session to post answers.
2. "Login" button must show instead of "Post answer" if user not logged in.
3. "Edit" or "Delete" button must show for author only.
4. Maybe add a confirmation button once user clicks on "Post answer"
5. Once confirmed, answer must be recorded in database.

**Comment by Lercerss** [comment]
Implemented by #41.

**Comment by Belize22** [comment]
![issue 26](https://user-images.githubusercontent.com/14872794/37225064-6ca37c54-23a3-11e8-81ce-a611d6a03f28.png)
