### ISSUE TITLE
Implement TravisCI or similar CI for project

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/SOEN341W18#30]
## Description
Add a continuous integration (CI) service for this project. The goal is to automate the testing for every release or versions of this project during each iteration. The convenient choice would be Travis CI.
  - Story points: 3
  - Priority: High
  - Risk: Medium

## Tasks (test out with an exercise) 
  1. Fork from given repo url: https://github.com/swy351/TravisExercise
  1. Enable connection between Travis and this GitHub repository.
  1. Locally clone the repo
  1. Add a **.travis.yml** file
  1. Push a build break into the fork

## Tasks for our repository
  1. Repeat the exercise but for project repo
  1. Create empty tests

## Acceptance Test
  1. Build has to be detected by Travis CI
  1. Empty tests are available through Travis CI for our project

**Comment by alvyn279** [comment]
I think only the owner of the repo can implement the TravisCI connection to the **SOEN341W18** repo.

**Comment by Lercerss** [comment]
Travis CI has been implemented as part of #31.

**Comment by niiita** [comment]
![image](https://user-images.githubusercontent.com/35353909/37231856-b4139d28-23ba-11e8-8dad-abca52af9c8a.png)
