### ISSUE TITLE
Extend user profile

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#32]
## Description
A user should be able to have a profile picture, email address, first name and last name. These should be modifiable from the user's profile page. A different user should not be able to see another user's personal information such as their email, first and last name.
  - Story points: 3
  - Priority: Low
  - Risk: Medium

## Tasks
  1. Extend the User object in the database to store additional information.
  1. Create a user profile page where the user can access his own information or another user's information.
  1. Validate authenticated user when accessing the user profile page to display different content.

## Acceptance Test
  1. Log in as a registered user.
  1. Access the user's profile page.
  1. Modify the profile picture, first and last name as well as the email address.
  1. Notice that the information is stored upon accessing the profile again.
  1. Access a different user's profile page.
  1. Notice that their public information is displayed.

**Comment by Belize22** [comment]
A potential idea to extend this feature would be to allow access to post history. Within post history, all the user's posts can be displayed or one can choose to filter it to questions only, answers only or comments only. Deciding accessibility to other users and those who don't have accounts can be discussed at a later point in time.

**Comment by 13rinda** [comment]
As we agreed, the profile picture feature is being omitted until further notices.

**Comment by niiita** [comment]
When signing up, user should be directed to edit profile page to build profile.

**Comment by Lercerss** [comment]
Issue implemented by #64.

**Comment by pvacca97** [comment]
![Acceptance Test](https://user-images.githubusercontent.com/35609091/37224862-b41f5392-23a2-11e8-801b-5685fb2f3283.png)
