### ISSUE TITLE
Refactor project settings

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#34]
## Description
The project settings found in SA3 should be moved into the qa_web directory to reduce clutter and group up application files. Since our project only uses 1 app, there is no need to have a separate project folder to store the settings and url configs.
  - Story points: 0
  - Priority: Medium
  - Risk: Low

## Tasks
  1. Move the settings module to qa_web.
  1. Add the 'admin/' path to the qa_web url config.
  1. Move the wsgi module to qa_web.
  1. Modify references to SA3 found in the settings, wsgi and manage modules to refer to qa_web.

## Acceptance Test
  1. The SA3 folder is no longer found in the repo.

**Comment by alvyn279** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues](https://trello.com/c/r2vP8ZKY/13-issues)

**Comment by alvyn279** [comment]
Look at full conversation in PR #91
