### ISSUE TITLE
Implement relational database tables (Models)

### ISSUE THREAD

**Issue by alvyn279** [Lercerss/SOEN341W18#35]
## Description
Create the different tables within the database. The relational structure and logic are both important for testing the features that are being implemented in Sprint 2. 
  - Story points: 3
  - Priority: High
  - Risk: Medium

## Tasks (_view comments below for referenced commits_)
  1. Add classes to `models.py` with necessary foreign keys for relational structure
  1. `python manage.py makemigrations`
  1. `python manage.py migrate`
  1. Add some testing data to Fields

## Acceptance Test
  1. Display one sample user with all relational data
  1. Core features successfully make use of data

**Comment by alvyn279** [comment]
Here is a general diagram of the database implemented in `models.py` 

![image](https://user-images.githubusercontent.com/29107916/36039733-61895d98-0d91-11e8-928a-8927e8864703.png)

**Comment by alvyn279** [comment]
## The relevant discussion is in PR #40. Please view it for further insight.

**Comment by alvyn279** [comment]
After multiple reviews and re-structuring the implementation of our classes in `models.py`, PR #40 has been merged. This represents the backbone of our backend structure.

**Comment by pvacca97** [comment]
![Acceptance Test](https://user-images.githubusercontent.com/35609091/37237006-b96848d4-23db-11e8-845f-64352c1a3044.png)
