### ISSUE TITLE
Edit Posts

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#43]
## Description
A user should be able to edit a question, answer or comment they posted.
  - Story points: 3
  - Priority: Medium
  - Risk: High

## Tasks
  1. Create template page with a form for editing a post.
  1. Add buttons to existing templates so a post's owner can access the editing page.

## Acceptance Test
  1. Log in as any user.
  1. Post a question.
  1. Access the question editing page with the provided edit button.
  1. Submit changes to the question's description or title.
  1. Notice that the changes have been saved.

**Comment by riyaGit** [comment]
I think this should be divided into 2 separate issues : "edit post" and "delete post".

**Comment by riyaGit** [comment]
Issue #66  edit post and issue #59 delete answers implemented
