### ISSUE TITLE
Log out

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#44]
## Description
A user should be able to log out after logging in.
  - Story points: 1.
  - Priority: High
  - Risk: Low

## Tasks
  1. Add a log out button to page headers.

## Acceptance Test
  1. Log in with any user.
  1. Notice that the log out button is now available.

**Comment by Belize22** [comment]
Good call on making this high priority. This will make testing much easier.

**Comment by pvacca97** [comment]
Conversation is in the Logout PR #61

**Comment by alvyn279** [comment]
![image](https://user-images.githubusercontent.com/29107916/38180300-9225e9ae-35f9-11e8-997d-75db859dbba1.png)
