### ISSUE TITLE
Ban Users

### ISSUE THREAD

**Issue by Belize22** [Lercerss/SOEN341W18#47]
## Description
Grant administrative users the ability to ban regular users for either a set amount of time or permanently.
  - Story points: 5
  - Priority: Medium
  - Risk: Medium

## Tasks
  1. Add "Ban User" button when administrator visits a profile associated with a regular user. If the user is
already banned, replace text value with "Check Ban Settings"
  2. Clicking the button above leads to a set ban page
  3. In Set Ban page, provide an option to ban the user for a set amount of time. This feature should contain input that allows the administrator to set a date (year, month, day, hour and minutes) for when the ban ends. Set a button saying "Temporarily Ban User" that acts as input to execute this
action. Validate that the ban date is not before the current date.
  4. In Set Ban page, provide an option to ban the user permanently. Input is just a button saying "Permanently Ban User"
  5. Put a textbox in the Set Ban page so the administrator can give reasoning on why he/she applied a
ban for the user. Make input required for this so administrators can't ban the user without reasoning.
  6. If the user is already banned, keep the reasoning text box for reasoning modification and a button that says "Unban User". If the ban is temporary, also keep the end date input so the date when the user is unbanned can be modified.
  7. For the profile page of a banned user, add an informative message stating that he/she has been banned, also displaying the reasoning the administrator provided via Task 5. If it's a temporary ban, display the date when they will be unbanned. Only the banned user in question should see this message!
  8. Ensure that banned users cannot ask questions, answer questions, comment on questions or vote.

## Acceptance Test
  1. Check an unbanned user profile as a user. Ensure "Ban User" does not appear.
  2. Repeat Step 1 except check an administrative profile as an administrator.
  3. Check an unbanned user profile as an administrator. Ensure "Ban User" appears.
  4. Click on "Ban User" and set a temporary ban with an end date before the current date. Ensure that the ban is not submitted, informing the administrator to provide a valid date when the ban ends
  5. Repeat Step 4 except provide an end date that is after the current date. Don't put anything in the reasoning text box. Ensure that the ban is not submitted, informing the user to provide a reason.
  6. Repeat Step 5 except provide input in the reasoning text box. Ensure that the ban is applied.
  7. Log out as the administrator and log in as the banned user. Check their profile to ensure that a message stating that they are banned, the reasoning provided by the administrator and the time they will be unbanned. Also check that input for asking questions, answering questions, commenting and voting are disabled.
  8. Log in as the administrator and go to the banned user's profile. Ensure that "Check Ban Settings" appears
  9. Click on "Check Ban Settings"
  10. Modify the end date to a different date that is after the current date. Modify the reasoning so that it's different from the current reasoning.
  11. Repeat Step 7. Ensure that the reasoning and ban date corresponds with the ones the administrator inputted in Step 10.
  12. Repeat Step 8-9.
  13. Click "Unban User"
  14. Repeat Step 7 except ensure that no message involving bans appear. Verify that input for asking questions, answering questions, commenting and voting are enabled.
  15. Repeat Steps 2-3
  16. Click "Permanently Ban User" but don't provide any input in the reasoning text box. Ensure that the ban is not submitted, informing the user to provide a reason.
  17. Repeat Step 16 except provide input in the reasoning text box. Ensure that the ban is submitted.
  18. Repeat Steps 7-9. For Step 7, ensure that no unban time appears in the message.
  19. Repeat Step 10 except ensure that the input for end date modification does not appear. Modify the reasoning so that it's different from the current reasoning.
  20. Repeat Step 7-9.  For Step 7, ensure that no unban time appears in the message and that the reasoning corresponds to the administrator's modifications in Step 19.
  21. Click "Unban User"
  22. Repeat Step 14.

**Comment by Lercerss** [comment]
Will not be implemented.
