### ISSUE TITLE
Count number of views to a question

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#54]
## Description
A user should be able to know how many views a question has had.
  - Story points: 2
  - Priority: Medium
  - Risk: Medium

## Tasks
  1. Increment number of views on a question when it is displayed to a user.
  1. Display number of views on question's page.

## Acceptance Test
  1. Browse to the question index page.
  1. Open any question.
  1. Notice that the number of views is displayed.
  1. View the page multiple times.
  1. Notice that the view count increases.

**Comment by alvyn279** [comment]
In terms of requirements, it seems that we want to edge towards a structure where the number of views is counted if the user is logged in. **However, we would not limit the count to only one view per user. Every time a logged in user opens the question page, it should count as one view.** If a non-logged in user opens the page, the view count will not increase by one. I will be implementing it with this mentality. Correct me if I'm wrong, @Lercerss.

**Comment by alvyn279** [comment]
Issue is closed follow PR #58 . PLEASE REFER TO PR #58 FOR THE COMPLETE CONVERSATION.

**Comment by alvyn279** [comment]
Issue is closed follow PR #58 . PLEASE REFER TO PR #58 FOR THE COMPLETE CONVERSATION.

**Comment by jetcanfly** [comment]
![image](https://user-images.githubusercontent.com/18118928/37223787-97367ab0-239f-11e8-97f7-5589ece3ccca.png)

**Comment by jetcanfly** [comment]
![image](https://user-images.githubusercontent.com/18118928/37224066-5ee80970-23a0-11e8-8e18-62ad133c2fb8.png)
