### ISSUE TITLE
Unify front end theme usage

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#55]
## Description
Right now multiple themes and CSS/JS sources are being used for different pages. It would be best if the website used a single theme for all pages.
  - Story points: 3
  - Priority: High
  - Risk: High

## Tasks
  1. Remove unnecessary dependencies on themes.
  1. Fix page design where previous dependencies were removed.
  1. Refactor common HTML into a single base file.
  1. Make sure the navbar, header and footer are found in the base file.

**Comment by Lercerss** [comment]
As discussed during Feb 16th meeting, we should be using the bootstrap theme used for the homepage in all other pages of the website.

**Comment by Lercerss** [comment]
Implemented as part of #69.

**Comment by riyaGit** [comment]
![acceptancetest](https://user-images.githubusercontent.com/26652806/37224150-9cf7e1f4-23a0-11e8-8f48-2d4eddace8b6.png)
