### ISSUE TITLE
Ordering answers

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#57]
## Description
A user should be able to sort the amswers to a question based on score or creation date, in ascending or descending order.  
  - Story points: 2
  - Priority: High 
  - Risk: Low 

## Tasks
  1. Add buttons to select the different ways to sort answers to the template. 
  1. Add logic in the view to return the answers in a specific order. 

## Acceptance Test
  1. Access a question's page. 
  1. Use a button to sort the answers. 
  1. Notice that the answers are displayed in the requested order.

**Comment by Lercerss** [comment]
Implemented as part of #73.

**Comment by riyaGit** [comment]
![AcceptanceTest](https://user-images.githubusercontent.com/26652806/37224294-05106a7c-23a1-11e8-916d-6dcb55a11bc4.png)
