### ISSUE TITLE
Delete Posts

### ISSUE THREAD

**Issue by riyaGit** [Lercerss/SOEN341W18#59]
## Description
A user should be able to delete a question, answer or comment they posted.
  - Story points: 3
  - Priority: Medium
  - Risk: High

## Tasks
  1. Create template page with a form for deleting a post.
  1. Allow the owner to delete the post.

## Acceptance Test
  1. Log in as any user.
  1. Post a question.
  1. Delete the question
  1. Notice that the question does not appear in the index page anymore.

**Comment by alvyn279** [comment]
The relevant conversation can be observed in PR #96 .
