### ISSUE TITLE
Display post content using Markdown styling

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#63]
## Description
Markdown entered in a post's content should be properly formatted when the post is displayed again.
  - Story points: 3
  - Priority: Medium
  - Risk: High

## Tasks
  1. Add a rendering engine such as [Strapdownjs](http://strapdownjs.com/) to render post content in the template.
  1. Make sure special character strings are properly escaped.
  1. Apply the rendering to all posts that can use Markdown styling.

## Acceptance Test
  1. Post a question or answer using Markdown styling such as `## Header` or `**bold**`.
  1. Navigate to the question display page.
  1. Notice that the Markdown is properly displayed.

**Comment by alvyn279** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues](https://trello.com/c/r2vP8ZKY/13-issues)

**Comment by alvyn279** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issues](https://trello.com/c/r2vP8ZKY/13-issues)

**Comment by alvyn279** [comment]
At this point, the markdown editor does not work and is basically useless. When trying to affect some text in the answer question textbox with markdown, the cursor is brought up to another textbox, for commenting in this case..

**Comment by alvyn279** [comment]
I do not think Strapdownjs is what we are looking for in this case. Either we find a parser that handles the markdown content that is sent or we migrate the whole markdown system to a python library.

**Comment by alvyn279** [comment]
When looking at it right now, I will go about it the frontend way, as making API calls is not time efficient.

**Comment by alvyn279** [comment]
ALL THE RELEVANT CONVERSATION CAN BE FOUND IN PR #72.

**Comment by 13rinda** [comment]
<img width="568" alt="screen shot 2018-03-09 at 4 01 46 pm" src="https://user-images.githubusercontent.com/31190776/37224871-bc6f862a-23a2-11e8-8a47-8e471130d43b.png">
