### ISSUE TITLE
Edit Answers

### ISSUE THREAD

**Issue by riyaGit** [Lercerss/SOEN341W18#66]
## Description
A user should be able to edit a question, answer or comment they posted.
  - Story points: 3
  - Priority: Medium
  - Risk: High

## Tasks
  1. Create template page with a form for editing an answer.
  1. Add buttons to existing templates so a post's owner can access the editing page.

## Acceptance Test
  1. Log in as any user.
  1. Post a question.
  1. Access the answer editing page with the provided edit button.
  1. Submit changes to the answer.
  1. Notice that the changes have been saved.

**Comment by riyaGit** [comment]
Issue #66 Implemented and merged

**Comment by alvyn279** [comment]
![image](https://user-images.githubusercontent.com/29107916/38180182-8d467c4c-35f8-11e8-90da-52dc0b2037b8.png)
