### ISSUE TITLE
User Profile Extension, post history and picture

### ISSUE THREAD

**Issue by niiita** [Lercerss/SOEN341W18#68]
## Description
Implementing user profile picture and post history
  - Story points: 2
  - Priority: med
  - Risk: med

## Tasks

  1. Implement profile picture. Enable uploading.
  1. Show user posts log.
  1. Show user answers log.
  1. Show user comments log.
  1. Show user votes log.
  1. must add creation time for votes

## Acceptance Test

  1. Access profile page.
  1. Notice history is displayed.
  1. Upload picture.
  1. Notice picture on profile.

**Comment by Lercerss** [comment]
@niiita Do you think this will be done by Wednesday? If not feel free to change the milestone to Sprint 4, thank you!
