### ISSUE TITLE
Ordering Answers: URL parameters via GET request

### ISSUE THREAD

**Issue by Belize22** [Lercerss/SOEN341W18#76]
## Description
Allow the user to sort answers by a URL parameter (i.e. a user can put "highestScore" or "leastRecent" in the URL and it will sort answers by the desired category)
  - Story points: 2
  - Priority: Low
  - Risk: Low

## Tasks
  1. Convert POST request to a GET request for ordering answers
  2. Add sort by URL parameter for the URL to the answers page
  3. Order by highest score if the URL parameter isn't given a proper ordering category.

## Acceptance Test
  1. Go on an answer page for any question. Note that answers are ordered by highest score
  2. Ensure that changing the order by drop-down menu still works (i.e. Select "Least Recent" by drop down menu and ensure that the answers are ordered by least recent posts)
  3. Ensure that the proper URL parameter results in proper sorting (i.e. putting "leastRecent" in the URL parameter results in the answers being ordered by least recent posts)

**Comment by Lercerss** [comment]
Will not be implemented.
