### ISSUE TITLE
Edit button on Question id page

### ISSUE THREAD

**Issue by niiita** [Lercerss/SOEN341W18#77]
## Description
Edit button shows for questions
  - Story points: [1]
  - Priority: [Low]
  - Risk: [Low]

## Tasks
  1. Should make edit button display ONLY for the person who posted the question.
  1. Should  make edit buttons show up for answers and comments as well for the person who posted that comment/answer.

## Acceptance Test
  1. If the user is the poster, edit button shows else, just display time stamp and author with vote buttons.

**Comment by Lercerss** [comment]
Implemented as part of #89
