### ISSUE TITLE
Hide/Display Comment Box

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#79]
## Description
Move away from displaying all comment boxes when a user is logged in to allowing the user to press a button that will make the comment box appear or disappear, reducing clutter.
  - Story points: 2
  - Priority: High
  - Risk: Medium

## Tasks
  1. Add buttons to answerspage for toggling visibility of a comment box.
  1. Tie button click to toggling of an individual comment box's visibility attribute.

## Acceptance Test
  1. As a logged in user, access a question's answer page.
  1. Notice that no comment boxes are displayed.
  1. Click on an answer's comment button.
  1. Notice that the comment box for that answer is displayed.

**Comment by alvyn279** [comment]
I looked at your commit that performed the hiding and displaying of the box. I didn't test it out, but it seemed very complicated on the `JS` side. If you want to keep it that way then, it's fine but know that this can be done in an extremely simple and strictly front-end manner with [Bootstrap Collapse](https://www.w3schools.com/bootstrap/bootstrap_collapse.asp).

I think that using the framework's capacities is a good idea, not wanting to take away the effort you put into the manual `show()` and `hide()` for your already existing implementation.

**Comment by Belize22** [comment]
![issue 79](https://user-images.githubusercontent.com/14872794/37631858-d6e515ac-2bc1-11e8-8eac-244f5c86b0f5.png)
