### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#83]
## Description
We should report test coverage as a continuous integration feature. It should be displayed in the project's repo and reports on test coverage should be available.
  - Story points: 3
  - Priority: High
  - Risk: Medium

## Tasks
  1. Add coverage library to project such as `coverage.py`.
  1. Evaluate possible CI tools for coverage integration.
  1. Add coverage state in README as well as coverage reports.

**Comment by alvyn279** [comment]
I suggest we use `coverage.py`  module for this issue. Link to documentation is [here](https://docs.djangoproject.com/en/2.0/topics/testing/advanced/#integration-with-coverage-py)

**Comment by alvyn279** [comment]
Instead of using a python module such as `coverage.py`, it might be more interesting to use a service such as [Codecov](https://codecov.io/). This will generate a nice UI report as a comment on the necessary PRs and/or commits.

**Comment by Lercerss** [comment]
We will make use of `Codecov` to integrate coverage into our continuous integration. The `coverage.py` module will be used to generate coverage reports for Codecov to display.

**Comment by Lercerss** [comment]
Implemented as part of #90.
