### ISSUE TITLE
Asking question button on homepage does not redirect properly

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#92]
## Description
When a user that is not authenticated presses the "Click to ask a question" button on the homepage, they are redirected to the login page but after logging in they are not properly redirected to the asking a question page. This is due to the template linking directly to `/login/` instead of making use of proper redirecting with the views decorator `@login_required`.
  - Story points: 0
  - Priority: Low
  - Risk: Low

## Tasks
  1. Remove condition on url of `<a>` tag found in `home.html`'s header block.

**Comment by niiita** [comment]
I've fixed this issue on my branch (userProf_Ext2) but it hasn't been merged. I'll make a commit :)

**Comment by Lercerss** [comment]
@niiita Please take a look at #94

**Comment by Lercerss** [comment]
Implemented as part of #94.
