### ISSUE TITLE
Vote indicators

### ISSUE THREAD

**Issue by Lercerss** [Lercerss/SOEN341W18#95]
## Description
A user should be able to see if they have voted on a post previously. 
  - Story points: 2
  - Priority: High
  - Risk: Medium

## Tasks
  1. Add conditional style attributes to voting buttons on each post. 
  1. Pass context values from the view to allow selection of which buttons to highlight. 

## Acceptance Test
  1. Upvote an answer. 
  1. Notice that the score increases and the button is now different.
  1. Downvote an answer.
  1. Notice that the downvote button is now different and the upvote is back to its original state.

**Comment by Belize22** [comment]
![issue 95](https://user-images.githubusercontent.com/14872794/37749618-207feba8-2d5f-11e8-98bf-8b5bd57324d1.png)
